In [1]:
import torch

In [2]:
# ---------------------------
# 1. Tensor Creation
# ---------------------------
print("=== 1. Tensor Creation ===")

=== 1. Tensor Creation ===


In [3]:
# I have created a tensor from a Python list.
tensor_from_list = torch.tensor([1, 2, 3])
print("Tensor from List:", tensor_from_list)

Tensor from List: tensor([1, 2, 3])


In [4]:
# I have created tensors filled with zeros and ones.
zeros_tensor = torch.zeros((2, 3))  # A 2x3 tensor filled with zeros
ones_tensor = torch.ones((2, 3))    # A 2x3 tensor filled with ones
print("Zeros Tensor:\n", zeros_tensor)
print("Ones Tensor:\n", ones_tensor)

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# I have generated tensors with random values from uniform and normal distributions.
random_uniform = torch.rand(2, 3)  # Random values between [0, 1)
random_normal = torch.randn(2, 3)  # Random values from a normal distribution (mean=0, std=1)
print("Random Uniform Tensor:\n", random_uniform)
print("Random Normal Tensor:\n", random_normal)

Random Uniform Tensor:
 tensor([[0.8995, 0.2085, 0.8515],
        [0.1644, 0.3759, 0.6203]])
Random Normal Tensor:
 tensor([[-1.7250, -0.6158,  1.4456],
        [-0.6506, -0.3062,  0.2288]])


In [6]:
# I have created a tensor with a range of values using `torch.arange`.
range_tensor = torch.arange(1, 10, 2)  # Start=1, End=10, Step=2
print("Range Tensor:", range_tensor)

Range Tensor: tensor([1, 3, 5, 7, 9])


In [7]:
# I have created a tensor filled with a fixed value using `torch.full`.
full_tensor = torch.full((2, 3), fill_value=5)  # A 2x3 tensor filled with the value 5
print("Full Tensor (filled with 5):\n", full_tensor)

Full Tensor (filled with 5):
 tensor([[5, 5, 5],
        [5, 5, 5]])


In [8]:
# ---------------------------
# 2. Tensor Operations
# ---------------------------
print("\n=== 2. Tensor Operations ===")


=== 2. Tensor Operations ===


In [9]:
# I have performed arithmetic operations like addition and multiplication.
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])
addition = x + y
multiplication = x * y
print("Addition:", addition)
print("Element-wise Multiplication:", multiplication)

Addition: tensor([5., 7., 9.])
Element-wise Multiplication: tensor([ 4., 10., 18.])


In [10]:
# I have performed matrix multiplication using `torch.matmul`.
matrix1 = torch.randn(2, 3)
matrix2 = torch.randn(3, 4)
matmul_result = torch.matmul(matrix1, matrix2)
print("Matrix Multiplication Result:\n", matmul_result)

Matrix Multiplication Result:
 tensor([[ 0.4236, -0.2747, -0.2454, -2.4199],
        [-1.7167, -0.4718, -0.6781,  1.8627]])


In [11]:
# I have performed matrix multiplication using `torch.matmul`.
matrix1 = torch.randn(2, 3)
matrix2 = torch.randn(3, 4)
matmul_result = torch.matmul(matrix1, matrix2)
print("Matrix Multiplication Result:\n", matmul_result)

Matrix Multiplication Result:
 tensor([[ 0.5320, -0.2741, -0.2659, -0.4926],
        [ 0.6934, -1.0684,  2.0202,  3.2201]])


In [12]:
# I have concatenated tensors along rows and stacked them along a new dimension.
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])
concatenated = torch.cat((t1, t2), dim=0)  # Concatenate along rows
stacked = torch.stack((t1, t2), dim=0)  # Stack along a new dimension
print("Concatenated Tensor:\n", concatenated)
print("Stacked Tensor:\n", stacked)

Concatenated Tensor:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Stacked Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [13]:
# I have demonstrated broadcasting by adding a scalar-like tensor to a vector.
b = torch.tensor([1, 2, 3])
c = torch.tensor([10])  # Scalar-like tensor
broadcasted = b + c  # Add scalar-like tensor to vector
print("Broadcasted Addition:", broadcasted)

Broadcasted Addition: tensor([11, 12, 13])


In [14]:
# I have applied element-wise mathematical functions like exp, log, and sqrt.
exp_tensor = torch.exp(random_uniform)  # Exponential function
log_tensor = torch.log(torch.abs(random_normal))  # Logarithmic function (avoid log(0))
sqrt_tensor = torch.sqrt(torch.abs(random_uniform))  # Square root function
print("Exponential Tensor:\n", exp_tensor)
print("Logarithmic Tensor:\n", log_tensor)
print("Square Root Tensor:\n", sqrt_tensor)

Exponential Tensor:
 tensor([[2.4584, 1.2318, 2.3431],
        [1.1787, 1.4562, 1.8595]])
Logarithmic Tensor:
 tensor([[ 0.5453, -0.4849,  0.3686],
        [-0.4298, -1.1836, -1.4750]])
Square Root Tensor:
 tensor([[0.9484, 0.4566, 0.9228],
        [0.4055, 0.6131, 0.7876]])


In [15]:
# I have computed reduction operations like sum, mean, and max.
sum_result = random_uniform.sum()
mean_result = random_uniform.mean()
max_result = random_uniform.max()
print("Sum:", sum_result)
print("Mean:", mean_result)
print("Max:", max_result)

Sum: tensor(3.1200)
Mean: tensor(0.5200)
Max: tensor(0.8995)


In [16]:
# ---------------------------
# 3. Indexing and Slicing
# ---------------------------
print("\n=== 3. Indexing and Slicing ===")



=== 3. Indexing and Slicing ===


In [17]:
# I have indexed and sliced tensors to access specific elements, rows, and columns.
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Tensor:\n", tensor)
print("First Row:", tensor[0])  # First row
print("Second Column:", tensor[:, 1])  # Second column
print("Sub-tensor:\n", tensor[1:, :2])  # Rows 1 and 2, Columns 0 and 1

Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
First Row: tensor([1, 2, 3])
Second Column: tensor([2, 5, 8])
Sub-tensor:
 tensor([[4, 5],
        [7, 8]])


In [18]:
# I have used advanced indexing techniques like `torch.index_select` and `torch.gather`.
indices = torch.tensor([0, 2])  # Indices to select
selected_rows = torch.index_select(tensor, dim=0, index=indices)  # Select specific rows
print("Selected Rows (using index_select):\n", selected_rows)
gathered_elements = torch.gather(tensor, dim=1, index=torch.tensor([[0, 2], [1, 2], [0, 1]]))
print("Gathered Elements (using gather):\n", gathered_elements)


Selected Rows (using index_select):
 tensor([[1, 2, 3],
        [7, 8, 9]])
Gathered Elements (using gather):
 tensor([[1, 3],
        [5, 6],
        [7, 8]])


In [22]:
#---------------------------
# 4. Boolean Masking and Comparison
# ---------------------------
print("\n=== 4. Boolean Masking and Comparison ===")


=== 4. Boolean Masking and Comparison ===


In [23]:
# I have compared tensors using comparison operators like `>`.
comparison = random_uniform > 0.5
print("Comparison Tensor (values > 0.5):\n", comparison)

Comparison Tensor (values > 0.5):
 tensor([[ True, False,  True],
        [False, False,  True]])


In [24]:
# I have applied boolean masking to filter tensor values.
masked_values = random_uniform[comparison]
print("Masked Values (values > 0.5):", masked_values)


Masked Values (values > 0.5): tensor([0.8995, 0.8515, 0.6203])


In [25]:
# I have used logical operations like AND, OR, and NOT on boolean tensors.
logical_and = torch.logical_and(torch.tensor([True, False, True]), torch.tensor([False, False, True]))
logical_or = torch.logical_or(torch.tensor([True, False, True]), torch.tensor([False, False, True]))
logical_not = torch.logical_not(torch.tensor([True, False, True]))
print("Logical AND:", logical_and)
print("Logical OR:", logical_or)
print("Logical NOT:", logical_not)

Logical AND: tensor([False, False,  True])
Logical OR: tensor([ True, False,  True])
Logical NOT: tensor([False,  True, False])


In [26]:
# ---------------------------
# 5. Sorting and Top-k Elements
# ---------------------------
print("\n=== 5. Sorting and Top-k Elements ===")


=== 5. Sorting and Top-k Elements ===


In [27]:
# I have sorted tensors using `torch.sort`.
sorted_tensor, indices = torch.sort(random_uniform, dim=1, descending=True)
print("Sorted Tensor:\n", sorted_tensor)

Sorted Tensor:
 tensor([[0.8995, 0.8515, 0.2085],
        [0.6203, 0.3759, 0.1644]])


In [28]:
# I have found the top-k elements in a tensor using `torch.topk`.
topk_values, topk_indices = torch.topk(random_uniform, k=2, dim=1)
print("Top-2 Values:\n", topk_values)
print("Top-2 Indices:\n", topk_indices)


Top-2 Values:
 tensor([[0.8995, 0.8515],
        [0.6203, 0.3759]])
Top-2 Indices:
 tensor([[0, 2],
        [2, 1]])


In [29]:
# ---------------------------
# 6. Padding and Splitting
# ---------------------------
print("\n=== 6. Padding and Splitting ===")


=== 6. Padding and Splitting ===


In [30]:
# I have added padding to a tensor using `torch.nn.functional.pad`.
padded_tensor = torch.nn.functional.pad(tensor, pad=(1, 1, 1, 1), mode='constant', value=0)
print("Padded Tensor:\n", padded_tensor)

Padded Tensor:
 tensor([[0, 0, 0, 0, 0],
        [0, 1, 2, 3, 0],
        [0, 4, 5, 6, 0],
        [0, 7, 8, 9, 0],
        [0, 0, 0, 0, 0]])


In [31]:
# I have split a tensor into smaller chunks using `torch.split`.
split_tensors = torch.split(tensor, split_size_or_sections=1, dim=0)
print("Split Tensors:")
for i, t in enumerate(split_tensors):
    print(f"Chunk {i}:\n", t)

Split Tensors:
Chunk 0:
 tensor([[1, 2, 3]])
Chunk 1:
 tensor([[4, 5, 6]])
Chunk 2:
 tensor([[7, 8, 9]])


In [32]:
# ---------------------------
# 7. Special Functions and Transformations
# ---------------------------
print("\n=== 7. Special Functions and Transformations ===")



=== 7. Special Functions and Transformations ===


In [33]:
# I have applied trigonometric functions like sin, cos, and tanh to tensors.
sin_tensor = torch.sin(random_uniform)
cos_tensor = torch.cos(random_uniform)
tanh_tensor = torch.tanh(random_uniform)
print("Sine Tensor:\n", sin_tensor)
print("Cosine Tensor:\n", cos_tensor)
print("Hyperbolic Tangent Tensor:\n", tanh_tensor)

Sine Tensor:
 tensor([[0.7830, 0.2070, 0.7523],
        [0.1637, 0.3671, 0.5813]])
Cosine Tensor:
 tensor([[0.6220, 0.9783, 0.6589],
        [0.9865, 0.9302, 0.8137]])
Hyperbolic Tangent Tensor:
 tensor([[0.7161, 0.2055, 0.6918],
        [0.1629, 0.3591, 0.5513]])


In [34]:
# I have permuted and transposed tensor dimensions using `tensor.permute` and `tensor.transpose`.
permuted_tensor = tensor.permute(1, 0)  # Swap dimensions
transposed_tensor = tensor.transpose(0, 1)  # Transpose dimensions
print("Permuted Tensor:\n", permuted_tensor)
print("Transposed Tensor:\n", transposed_tensor)

Permuted Tensor:
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
Transposed Tensor:
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [35]:
# I have clamped tensor values within a specified range using `torch.clamp`.
clamped_tensor = random_uniform.clamp(min=0.2, max=0.8)
print("Clamped Tensor (values restricted between 0.2 and 0.8):\n", clamped_tensor)


Clamped Tensor (values restricted between 0.2 and 0.8):
 tensor([[0.8000, 0.2085, 0.8000],
        [0.2000, 0.3759, 0.6203]])


In [36]:
# ---------------------------
# 8. Type Conversion and Device Management
# ---------------------------
print("\n=== 8. Type Conversion and Device Management ===")



=== 8. Type Conversion and Device Management ===


In [37]:
# I have converted a tensor's data type using `tensor.to`.
float_tensor = torch.tensor([1.0, 2.0, 3.0])
int_tensor = float_tensor.to(torch.int32)
print("Float Tensor:", float_tensor)
print("Converted to Int Tensor:", int_tensor)

Float Tensor: tensor([1., 2., 3.])
Converted to Int Tensor: tensor([1, 2, 3], dtype=torch.int32)


In [38]:
# I have moved a tensor to GPU if CUDA is available using `tensor.to(device)`.
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor_on_gpu = random_uniform.to(device)
    print("Tensor moved to GPU:", tensor_on_gpu)
else:
    print("GPU not available, skipping device management.")

GPU not available, skipping device management.


In [39]:
# ---------------------------
# 9. Miscellaneous Features
# ---------------------------
print("\n=== 9. Miscellaneous Features ===")


=== 9. Miscellaneous Features ===


In [40]:
# I have computed cumulative sums and products using `torch.cumsum` and `torch.cumprod`.
cumsum_tensor = torch.cumsum(random_uniform, dim=1)
cumprod_tensor = torch.cumprod(random_uniform, dim=1)
print("Cumulative Sum:\n", cumsum_tensor)
print("Cumulative Product:\n", cumprod_tensor)

Cumulative Sum:
 tensor([[0.8995, 1.1080, 1.9595],
        [0.1644, 0.5403, 1.1606]])
Cumulative Product:
 tensor([[0.8995, 0.1875, 0.1597],
        [0.1644, 0.0618, 0.0383]])


In [41]:
# I have found unique values and their counts using `torch.unique`.
unique_values, counts = torch.unique(tensor, return_counts=True)
print("Unique Values in Tensor:", unique_values)
print("Counts of Unique Values:", counts)


Unique Values in Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Counts of Unique Values: tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])


In [42]:
# I have computed the outer product of two tensors using `torch.outer`.
outer_product = torch.outer(x, y)
print("Outer Product of Tensors:\n", outer_product)


Outer Product of Tensors:
 tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])


In [43]:
# I have found the indices of maximum and minimum values using `torch.argmax` and `torch.argmin`.
argmax_value = torch.argmax(tensor)
argmin_value = torch.argmin(tensor)
print("Index of Maximum Value:", argmax_value)
print("Index of Minimum Value:", argmin_value)


Index of Maximum Value: tensor(8)
Index of Minimum Value: tensor(0)


In [44]:
# I have found the indices of maximum and minimum values using `torch.argmax` and `torch.argmin`.
argmax_value = torch.argmax(tensor)
argmin_value = torch.argmin(tensor)
print("Index of Maximum Value:", argmax_value)
print("Index of Minimum Value:", argmin_value)


Index of Maximum Value: tensor(8)
Index of Minimum Value: tensor(0)


In [45]:
# I have created and manipulated sparse tensors using `torch.sparse_coo_tensor`.
indices = torch.tensor([[0, 1, 1], [2, 0, 2]])
values = torch.tensor([3, 4, 5], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(2, 3))
dense_tensor = sparse_tensor.to_dense()
print("Sparse Tensor (COO format):\n", sparse_tensor)
print("Dense Tensor from Sparse Tensor:\n", dense_tensor)


Sparse Tensor (COO format):
 tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)
Dense Tensor from Sparse Tensor:
 tensor([[0., 0., 3.],
        [4., 0., 5.]])


In [46]:
# I have demonstrated tensor broadcasting rules by adding tensors of different shapes.
broadcast_tensor = torch.tensor([[1, 2, 3]])  # Shape: (1, 3)
broadcasted_result = broadcast_tensor + torch.tensor([10, 20, 30])  # Shape: (3,)
print("Broadcasted Tensor:\n", broadcasted_result)

Broadcasted Tensor:
 tensor([[11, 22, 33]])


In [47]:
# I have normalized a tensor along a dimension using `torch.nn.functional.normalize`.
normalized_tensor = torch.nn.functional.normalize(random_uniform, p=2, dim=1)  # L2 normalization
print("Normalized Tensor:\n", normalized_tensor)


Normalized Tensor:
 tensor([[0.7161, 0.1660, 0.6779],
        [0.2211, 0.5054, 0.8341]])


In [48]:
# I have one-hot encoded categorical labels using `torch.nn.functional.one_hot`.
labels = torch.tensor([0, 2, 1])
one_hot = torch.nn.functional.one_hot(labels, num_classes=3)
print("One-hot Encoded Tensor:\n", one_hot)


One-hot Encoded Tensor:
 tensor([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]])


In [49]:
# I have handled missing values (NaNs) in a tensor using boolean masks.
nan_tensor = torch.tensor([1.0, float('nan'), 3.0])
mask = ~torch.isnan(nan_tensor)
clean_tensor = nan_tensor[mask]
print("Tensor with NaNs:", nan_tensor)
print("Cleaned Tensor (NaNs removed):", clean_tensor)


Tensor with NaNs: tensor([1., nan, 3.])
Cleaned Tensor (NaNs removed): tensor([1., 3.])


In [50]:
# I have chunked a tensor into equal-sized pieces using `torch.chunk`.
chunked_tensors = torch.chunk(tensor, chunks=3, dim=0)
print("Chunked Tensors:")
for i, chunk in enumerate(chunked_tensors):
    print(f"Chunk {i}:\n", chunk)

Chunked Tensors:
Chunk 0:
 tensor([[1, 2, 3]])
Chunk 1:
 tensor([[4, 5, 6]])
Chunk 2:
 tensor([[7, 8, 9]])


In [51]:
# I have flattened a tensor into a 1D array using `tensor.flatten`.
flattened_tensor = tensor.flatten()
print("Flattened Tensor:", flattened_tensor)


Flattened Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [52]:
# I have repeated and tiled a tensor using `tensor.repeat` and `tensor.expand`.
repeated_tensor = tensor.repeat(2, 3)  # Repeat tensor along dimensions
tiled_tensor = tensor.unsqueeze(0).expand(2, -1, -1)  # Tile tensor
print("Repeated Tensor:\n", repeated_tensor)
print("Tiled Tensor:\n", tiled_tensor)


Repeated Tensor:
 tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9, 7, 8, 9],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9, 7, 8, 9]])
Tiled Tensor:
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [53]:
# I have extracted and created diagonal matrices using `torch.diagonal` and `torch.diag_embed`.
diagonal = torch.diagonal(tensor)  # Extract diagonal elements
print("Diagonal of Tensor:", diagonal)
modified_diagonal = tensor.diag_embed()  # Create a diagonal matrix
print("Diagonal Matrix from Tensor:\n", modified_diagonal)


Diagonal of Tensor: tensor([1, 5, 9])
Diagonal Matrix from Tensor:
 tensor([[[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]],

        [[4, 0, 0],
         [0, 5, 0],
         [0, 0, 6]],

        [[7, 0, 0],
         [0, 8, 0],
         [0, 0, 9]]])


In [54]:
# I have applied conditional operations using `torch.where`.
condition = tensor > 5
where_tensor = torch.where(condition, tensor, torch.zeros_like(tensor))  # Replace values <= 5 with 0
print("Tensor after applying `where` function:\n", where_tensor)


Tensor after applying `where` function:
 tensor([[0, 0, 0],
        [0, 0, 6],
        [7, 8, 9]])


In [55]:
# I have computed histograms of tensor values using `torch.histc`.
histogram = torch.histc(random_uniform, bins=5, min=0, max=1)
print("Histogram of Tensor Values:", histogram)

Histogram of Tensor Values: tensor([1., 2., 0., 1., 2.])


In [56]:
# I have created coordinate grids using `torch.meshgrid`.
x = torch.linspace(0, 1, 3)
y = torch.linspace(0, 1, 3)
grid_x, grid_y = torch.meshgrid(x, y, indexing='ij')
print("Meshgrid X:\n", grid_x)
print("Meshgrid Y:\n", grid_y)

Meshgrid X:
 tensor([[0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000]])
Meshgrid Y:
 tensor([[0.0000, 0.5000, 1.0000],
        [0.0000, 0.5000, 1.0000],
        [0.0000, 0.5000, 1.0000]])


In [57]:
# I have performed Einstein summation using `torch.einsum`.
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
einsum_result = torch.einsum('ij,jk->ik', a, b)  # Matrix multiplication
print("Einsum Result (Matrix Multiplication):\n", einsum_result)


Einsum Result (Matrix Multiplication):
 tensor([[19, 22],
        [43, 50]])


In [60]:
# I have scattered values into a tensor at specified indices using `tensor.scatter`.
scatter_tensor = torch.zeros(3, 5, dtype=torch.int64)  # Ensure dtype matches `values`
indices = torch.tensor([[0, 1, 2], [0, 1, 4]])
values = torch.tensor([[1, 2, 3], [4, 5, 6]])
scattered = scatter_tensor.scatter(dim=1, index=indices, src=values)
print("Scattered Tensor:\n", scattered)

Scattered Tensor:
 tensor([[1, 2, 3, 0, 0],
        [4, 5, 0, 0, 6],
        [0, 0, 0, 0, 0]])


In [61]:
# I have replaced tensor elements based on a mask using `tensor.masked_fill`.
masked_fill_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
mask = torch.tensor([[True, False, True], [False, True, False]])
filled_tensor = masked_fill_tensor.masked_fill(mask, value=-1)
print("Masked Fill Tensor:\n", filled_tensor)

Masked Fill Tensor:
 tensor([[-1,  2, -1],
        [ 4, -1,  6]])
